services:
  - type: web
    name: qarticle
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://qarticle_user:xuWZpQ2vPaqxOEsR2VP74fpPsCoGQOV5@dpg-d8pqqlpkh4rs739h0q8g-a/qarticle
        fromDatabase:
          name: qarticle_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: qarticle_redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: qarticle_db
    plan: free

redis:
  - name: qarticle_redis
    plan: free